export type ArticleSection = { heading: string; paragraphs: string[]; points?: string[] };

// Editorial additions for the existing articles. Backend content remains authoritative.
export const blogExtensions: Record<string, ArticleSection[]> = {
  "how-ai-agents-are-changing-business-workflows": [
    { heading: "Where an AI agent fits into a workflow", paragraphs: ["A useful starting point is a repeatable task with a clear outcome: reviewing an incoming request, finding the relevant information, and preparing a response. An agent can coordinate these steps, while people retain responsibility for decisions that need judgment.", "For example, a support workflow might retrieve a customer’s order, check the support policy, and draft a reply. Issuing a refund or changing an account should remain behind explicit permissions and approval rules."], points: ["Choose one workflow with a measurable outcome.", "Give the agent access only to the tools and information it needs.", "Keep approval steps for sensitive or irreversible actions."] },
    { heading: "Build the foundations before adding autonomy", paragraphs: ["Reliable automation starts with reliable inputs. Teams need clear ownership of their data, consistent interfaces to business systems, and a way to trace what happened at each step. An agent cannot compensate for missing records or an unclear process.", "Separate the ability to propose an action from the authority to execute it. This makes it easier to review results, diagnose failures, and introduce automation gradually rather than handing over an entire process at once."] },
    { heading: "Measure the quality of the result", paragraphs: ["Evaluate an agent against the workflow it is meant to improve. Track completion rates, the number of corrections people make, time saved, and the cost of each completed task. A fast response is useful only when the resulting action is correct.", "Start with a supervised pilot. Review both successful and failed cases, improve the instructions and tool interfaces, and expand the scope when the evidence supports it."] },
  ],
  "future-of-generative-ai": [
    { heading: "From generated output to useful work", paragraphs: ["The value of generative AI depends on how well its output serves a real task. A draft, summary, or software suggestion becomes useful when someone can review it, correct it, and apply it within an existing workflow.", "Teams should begin with a specific need rather than a broad ambition to add AI everywhere. Preparing a first draft of a document or summarizing an internal knowledge base creates a clearer starting point than trying to automate an entire business function."] },
    { heading: "Keep business context close to the system", paragraphs: ["Generic answers often lack the information an organization needs. Connecting a system to approved documents and relevant records can make its responses more useful, but access controls and source quality still matter.", "Make it clear which information informed an answer and when a person needs to verify it. Generated text should not be treated as proof that a statement is correct."], points: ["Use approved sources with clear ownership.", "Respect the same access boundaries as the underlying systems.", "Review outputs before using them in consequential decisions."] },
    { heading: "A practical way to adopt generative AI", paragraphs: ["Define the expected output, gather representative examples, and compare results against a baseline. Include difficult cases, not just the examples that produce an impressive demonstration.", "Treat the application as a system that needs ongoing maintenance. Changes to documents, prompts, models, and integrations should be evaluated before they reach users."] },
  ],
  "ai-in-modern-business": [
    { heading: "Start with the business problem", paragraphs: ["AI initiatives need a clear purpose: helping a team find information, reducing repetitive processing, or improving the consistency of a decision-support workflow. Define the problem and the expected outcome before selecting a tool.", "A small, well-scoped application is easier to evaluate. Identify who will use it, what inputs it needs, and how its results will be checked."] },
    { heading: "Examples of practical applications", paragraphs: ["An internal assistant can help employees locate approved policies. A document workflow can prepare extracted information for review. A reporting assistant can summarize an existing dashboard while linking back to the original figures."], points: ["Knowledge discovery with references to source documents.", "Document processing with a human review stage.", "Operational summaries based on verified business data."] },
    { heading: "Introduce AI with clear ownership", paragraphs: ["Assign responsibility for the data, the application, and the decisions made with its output. Users need to know how to report a mistake and when to use a manual process.", "Monitor quality alongside cost and speed. Continue an implementation when it makes the workflow more useful and dependable, and revise it when the evidence shows otherwise."] },
  ],
};
